# Starter pipeline

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: A
  jobs:
  - job: A1
    steps:
    - script: echo "A1"

  - job: A2
    steps:
    - script: echo "A2"

- stage: B
  dependsOn: [] 
  jobs:
  - job: B1
    steps:
    - script: echo "B1"
  
  - job: B2
    steps:
    - script: echo "B2"


